#!/usr/bin/env bash
# graduation-scan.sh — nightly-candidate scan for prose that should graduate
# into _shared/. Computes Jaccard similarity on 50-token shingles across every
# */SKILL.md and */modes/*.md pair. Flags pairs with similarity > 0.7 and
# opens a GitHub issue per cluster (idempotent — skips if an open issue with
# a matching title already exists).

set -u
umask 022

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)
REPO_ROOT=$(cd "$SCRIPT_DIR/.." && pwd)
THRESHOLD="${GRADUATION_THRESHOLD:-0.7}"
SHINGLE_LEN=50

list_files() {
  find "$REPO_ROOT" -mindepth 2 -maxdepth 2 -type f -name 'SKILL.md' 2>/dev/null
  find "$REPO_ROOT" -mindepth 3 -maxdepth 3 -type f -path '*/modes/*.md' 2>/dev/null
}

# Emit one token per line from a file's prose (frontmatter + code blocks
# stripped). Lowercase; alphanumeric only.
tokenize() {
  local file="$1"
  awk '
    BEGIN { in_fm=0; in_code=0 }
    NR==1 && $0=="---" { in_fm=1; next }
    in_fm==1 && $0=="---" { in_fm=0; next }
    in_fm==1 { next }
    /^```/ { in_code = 1 - in_code; next }
    in_code==1 { next }
    { print }
  ' "$file" \
    | tr '[:upper:]' '[:lower:]' \
    | tr -c '[:alnum:]' '\n' \
    | sed '/^$/d'
}

# Emit shingle fingerprints (one per line) for a file.
shingles() {
  local file="$1"
  tokenize "$file" | awk -v n="$SHINGLE_LEN" '
    { buf[NR%n] = $0;
      if (NR >= n) {
        s = ""
        for (i = 1; i <= n; i++) s = s buf[(NR+i)%n] " "
        print s
      }
    }'
}

issue_exists() {
  local title="$1"
  command -v gh >/dev/null 2>&1 || return 1
  gh issue list --state open --search "in:title \"$title\"" --json title 2>/dev/null \
    | grep -Fq "\"title\":\"$title\""
}

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

# Precompute shingle sets per file.
while IFS= read -r f; do
  [ -z "$f" ] && continue
  rel="${f#"$REPO_ROOT/"}"
  safe=$(printf '%s' "$rel" | tr '/' '_')
  shingles "$f" | sort -u > "$WORK/$safe.shingles"
  printf '%s\t%s\n' "$rel" "$WORK/$safe.shingles" >> "$WORK/index.tsv"
done < <(list_files)

# Pairwise Jaccard. Small set (≲30 files) so O(n²) is fine.
lines=$(wc -l < "$WORK/index.tsv" 2>/dev/null | tr -d ' ')
[ "${lines:-0}" -lt 2 ] && { printf 'nothing to compare\n'; exit 0; }

CANDIDATES="$WORK/candidates.txt"
: > "$CANDIDATES"

i=1
while IFS=$'\t' read -r rel_a file_a; do
  j=1
  while IFS=$'\t' read -r rel_b file_b; do
    if [ "$j" -le "$i" ]; then
      j=$((j+1)); continue
    fi
    inter=$(comm -12 "$file_a" "$file_b" | wc -l | tr -d ' ')
    [ "$inter" -eq 0 ] && { j=$((j+1)); continue; }
    union=$(sort -u "$file_a" "$file_b" | wc -l | tr -d ' ')
    [ "$union" -eq 0 ] && { j=$((j+1)); continue; }
    sim=$(awk -v a="$inter" -v u="$union" 'BEGIN { printf "%.3f", a/u }')
    over=$(awk -v s="$sim" -v t="$THRESHOLD" 'BEGIN { print (s+0 > t+0) ? 1 : 0 }')
    if [ "$over" -eq 1 ]; then
      printf '%s\t%s\t%s\n' "$sim" "$rel_a" "$rel_b" >> "$CANDIDATES"
    fi
    j=$((j+1))
  done < "$WORK/index.tsv"
  i=$((i+1))
done < "$WORK/index.tsv"

if [ ! -s "$CANDIDATES" ]; then
  printf 'no graduation candidates above threshold %s\n' "$THRESHOLD"
  exit 0
fi

printf 'candidates (similarity > %s):\n' "$THRESHOLD"
cat "$CANDIDATES"

while IFS=$'\t' read -r sim rel_a rel_b; do
  title="Potential _shared/ graduation: $rel_a + $rel_b (similarity $sim)"
  if issue_exists "$title"; then
    printf 'skip (issue exists): %s\n' "$title"
    continue
  fi
  if command -v gh >/dev/null 2>&1; then
    gh issue create --title "$title" \
      --body "Pairwise Jaccard similarity of ${sim} on 50-token shingles between \`$rel_a\` and \`$rel_b\`.\n\nEvaluate whether the overlapping prose should graduate into a \`_shared/<topic>.md\` referenced from both files.\n\nGenerated by \`scripts/graduation-scan.sh\`." \
      --label "polish,theme/internal" >/dev/null 2>&1 \
      && printf 'opened: %s\n' "$title" \
      || printf 'warn: gh issue create failed for: %s\n' "$title" >&2
  else
    printf 'would open (gh not installed): %s\n' "$title"
  fi
done < "$CANDIDATES"
