#!/usr/bin/env bash
# shellcheck disable=SC2034
# This library reports evaluation state through FEATURE_BRANCH_POLICY_* globals.

feature_branch_policy_load_config() {
  local repo="${1:-}" project="" root="" studio_home="" config_file=""

  if [ -n "${STUDIO_FEATURE_CONFIG_FILE:-}" ]; then
    config_file="$STUDIO_FEATURE_CONFIG_FILE"
  else
    if [ -n "${STUDIO_FEATURE_CONFIG_PROJECT:-}" ]; then
      project="$STUDIO_FEATURE_CONFIG_PROJECT"
    elif [ -n "${PROJECT:-}" ]; then
      project="$PROJECT"
    elif [ -n "$repo" ]; then
      root=$(git -C "$repo" rev-parse --show-toplevel 2>/dev/null || true)
      [ -n "$root" ] && project=$(basename "$root")
    fi
    if [ -n "$project" ] && type resolve_studio_home_for_login_home >/dev/null 2>&1; then
      studio_home=$(resolve_studio_home_for_login_home "${HOME:?HOME required}" 2>/dev/null || true)
      [ -n "$studio_home" ] && config_file="$studio_home/$project/config/features.env"
    fi
  fi

  [ -n "$config_file" ] || return 0
  [ "${FEATURE_BRANCH_POLICY_CONFIG_LOADED_FILE:-}" = "$config_file" ] && return 0
  if [ -f "$config_file" ]; then
    FEATURE_BRANCH_POLICY_CONFIG_LOADED_FILE="$config_file"
    # Generated by scripts/manager-feature-config.sh as single-quoted shell literals.
    # shellcheck disable=SC1090
    . "$config_file"
  fi
}

feature_branch_policy_bool_enabled() {
  case "$1" in
    1|true|TRUE|yes|YES|on|ON) return 0 ;;
    *) return 1 ;;
  esac
}

feature_branch_policy_default_base() {
  printf '%s\n' "${STUDIO_BRANCH_POLICY_DEFAULT_BASE:-${STUDIO_RELEASE_BRANCH_DEFAULT_BASE:-main}}"
}

feature_branch_policy_release_branch_pattern() {
  if [ -n "${STUDIO_BRANCH_POLICY_RELEASE_BRANCH_PATTERN:-}" ]; then
    printf '%s\n' "$STUDIO_BRANCH_POLICY_RELEASE_BRANCH_PATTERN"
  elif [ -n "${STUDIO_RELEASE_BRANCH_PATTERN:-}" ]; then
    printf '%s\n' "$STUDIO_RELEASE_BRANCH_PATTERN"
  else
    printf 'release/{version}\n'
  fi
}

feature_branch_policy_allow_feature_off_feature() {
  feature_branch_policy_bool_enabled "${STUDIO_BRANCH_POLICY_ALLOW_FEATURE_OFF_FEATURE:-0}"
}

feature_branch_policy_merge_target_to_main() {
  feature_branch_policy_bool_enabled "${STUDIO_BRANCH_POLICY_MERGE_TARGET_TO_MAIN:-1}"
}

feature_branch_policy_worktree_gc_scope() {
  printf '%s\n' "${STUDIO_BRANCH_POLICY_WORKTREE_GC_SCOPE:-project}"
}

feature_branch_policy_worktree_disk_budget_mb() {
  printf '%s\n' "${STUDIO_BRANCH_POLICY_WORKTREE_DISK_BUDGET_MB:-10240}"
}

feature_branch_policy_resolve_compare_ref() {
  local repo="${1:?usage: feature_branch_policy_resolve_compare_ref <repo> <base-ref>}"
  local base_ref="${2:?base ref required}"

  if git -C "$repo" rev-parse --verify "origin/$base_ref" >/dev/null 2>&1; then
    printf 'origin/%s\n' "$base_ref"
    return 0
  fi
  if git -C "$repo" rev-parse --verify "$base_ref" >/dev/null 2>&1; then
    printf '%s\n' "$base_ref"
    return 0
  fi
  return 1
}

feature_branch_policy_default_base_ref() {
  local repo="${1:?usage: feature_branch_policy_default_base_ref <repo> <branch>}"
  local branch="${2:?branch required}"
  local candidate configured_base origin_head

  feature_branch_policy_load_config "$repo"

  configured_base=$(feature_branch_policy_default_base)
  if [ -n "$configured_base" ] && [ "$configured_base" != "$branch" ]; then
    if feature_branch_policy_resolve_compare_ref "$repo" "$configured_base" >/dev/null 2>&1; then
      printf '%s\n' "$configured_base"
      return 0
    fi
  fi

  origin_head=$(git -C "$repo" symbolic-ref --quiet --short refs/remotes/origin/HEAD 2>/dev/null || true)
  if [ -n "$origin_head" ]; then
    origin_head="${origin_head#origin/}"
    if [ "$origin_head" != "$branch" ] && feature_branch_policy_resolve_compare_ref "$repo" "$origin_head" >/dev/null 2>&1; then
      printf '%s\n' "$origin_head"
      return 0
    fi
  fi

  for candidate in main master trunk develop; do
    [ "$candidate" = "$branch" ] && continue
    if feature_branch_policy_resolve_compare_ref "$repo" "$candidate" >/dev/null 2>&1; then
      printf '%s\n' "$candidate"
      return 0
    fi
  done

  return 1
}

feature_branch_policy_evaluate() {
  local repo="${1:?usage: feature_branch_policy_evaluate <repo> <branch> [base-ref] [context-label]}"
  local branch="${2:?branch required}"
  local base_hint="${3:-}"
  local context_label="${4:-feature branch}"
  local compare_ref=""

  FEATURE_BRANCH_POLICY_STATUS="passed"
  FEATURE_BRANCH_POLICY_BASE_REF=""
  FEATURE_BRANCH_POLICY_COMPARE_REF=""
  FEATURE_BRANCH_POLICY_DETAIL=""

  feature_branch_policy_load_config "$repo"

  if is_protected_branch "$branch"; then
    FEATURE_BRANCH_POLICY_STATUS="skipped"
    FEATURE_BRANCH_POLICY_DETAIL="$context_label $branch is a protected integration/release branch; feature-branch merge-commit history is not audited here"
    return 0
  fi

  if [ -n "$base_hint" ]; then
    FEATURE_BRANCH_POLICY_BASE_REF="$base_hint"
  else
    FEATURE_BRANCH_POLICY_BASE_REF=$(feature_branch_policy_default_base_ref "$repo" "$branch" 2>/dev/null || true)
    if [ -z "$FEATURE_BRANCH_POLICY_BASE_REF" ]; then
      FEATURE_BRANCH_POLICY_STATUS="skipped"
      FEATURE_BRANCH_POLICY_DETAIL="$context_label $branch has no explicit integration base; skipped feature-branch merge-commit audit"
      return 0
    fi
  fi

  compare_ref=$(feature_branch_policy_resolve_compare_ref "$repo" "$FEATURE_BRANCH_POLICY_BASE_REF" 2>/dev/null || true)
  if [ -z "$compare_ref" ]; then
    FEATURE_BRANCH_POLICY_STATUS="skipped"
    FEATURE_BRANCH_POLICY_DETAIL="$context_label $branch could not resolve base ref $FEATURE_BRANCH_POLICY_BASE_REF locally or at origin/$FEATURE_BRANCH_POLICY_BASE_REF"
    return 0
  fi
  FEATURE_BRANCH_POLICY_COMPARE_REF="$compare_ref"

  if git -C "$repo" rev-list --merges "${compare_ref}..${branch}" 2>/dev/null | grep -q .; then
    FEATURE_BRANCH_POLICY_STATUS="failed"
    FEATURE_BRANCH_POLICY_DETAIL="$context_label $branch contains merge commits since $compare_ref; rebase or retarget dependent feature branches instead of merging feature-to-feature"
    return 1
  fi

  FEATURE_BRANCH_POLICY_DETAIL="$context_label $branch has no merge commits since $compare_ref"
  return 0
}
