#!/usr/bin/env bash
# manager-feature-config.sh - project-scoped Studio feature settings.

set -u
set -o pipefail
umask 077

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)
# shellcheck source=lib-paths.sh
# shellcheck disable=SC1091
. "$SCRIPT_DIR/lib-paths.sh"

PROJECT=""
DRY_RUN=0

usage() {
  cat <<'EOF'
Usage:
  scripts/manager-feature-config.sh [--project <slug>] list
  scripts/manager-feature-config.sh [--project <slug>] get <feature|setting>
  scripts/manager-feature-config.sh [--project <slug>] enable <feature> [options]
  scripts/manager-feature-config.sh [--project <slug>] disable <feature>
  scripts/manager-feature-config.sh [--project <slug>] set <setting> <value> [--dry-run]
  scripts/manager-feature-config.sh [--project <slug>] doctor [feature]

Feature options:
  --default-release-base <branch>  Required by release_branch_workflow
  --branch-pattern <pattern>       Required by release_branch_workflow; use {version}
  --dry-run                        Print writes without changing config

Preferred user-facing entrypoint:
  /dev-studio manager config ...
EOF
}

while [ $# -gt 0 ]; do
  case "$1" in
    --project) PROJECT="${2:?--project requires value}"; shift 2 ;;
    --dry-run) DRY_RUN=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) break ;;
  esac
done

COMMAND="${1:-}"
[ -n "$COMMAND" ] || { usage >&2; exit 2; }
shift

resolve_feature_project() {
  if [ -n "$PROJECT" ]; then
    printf '%s\n' "$PROJECT"
    return 0
  fi
  resolve_project
}

PROJECT=$(resolve_feature_project) || exit 2
STUDIO_HOME=$(resolve_studio_home_for_login_home "${HOME:?HOME required}")
CONFIG_DIR="${STUDIO_FEATURE_CONFIG_DIR:-$STUDIO_HOME/$PROJECT/config}"
CONFIG_FILE="${STUDIO_FEATURE_CONFIG_FILE:-$CONFIG_DIR/features.env}"

if [ -f "$CONFIG_FILE" ]; then
  # Generated by this script; values are single-quoted shell literals.
  # shellcheck disable=SC1090
  . "$CONFIG_FILE"
fi

quote_env() {
  local value="$1"
  value=${value//\'/\'\\\'\'}
  printf "'%s'" "$value"
}

value_of() {
  local key="$1"
  eval "printf '%s\n' \"\${$key:-}\""
}

feature_key() {
  case "$1" in
    release_branch_workflow) printf 'STUDIO_FEATURE_RELEASE_BRANCH_WORKFLOW\n' ;;
    *) return 1 ;;
  esac
}

feature_description() {
  case "$1" in
    release_branch_workflow) printf 'Manager release branch prepare/status/sync/PR workflow\n' ;;
    *) return 1 ;;
  esac
}

feature_exists() {
  feature_key "$1" >/dev/null 2>&1
}

feature_names() {
  printf '%s\n' release_branch_workflow
}

setting_key() {
  case "$1" in
    release_branch_workflow.default_release_base|default_release_base|default-release-base)
      printf 'STUDIO_RELEASE_BRANCH_DEFAULT_BASE\n'
      ;;
    release_branch_workflow.branch_pattern|branch_pattern|branch-pattern)
      printf 'STUDIO_RELEASE_BRANCH_PATTERN\n'
      ;;
    STUDIO_*)
      printf '%s\n' "$1"
      ;;
    *)
      return 1
      ;;
  esac
}

write_setting() {
  local key="$1" value="$2" quoted tmp
  quoted=$(quote_env "$value")
  printf -v "$key" '%s' "$value"
  if [ "$DRY_RUN" -eq 1 ]; then
    printf '%s=%s\n' "$key" "$quoted"
    return 0
  fi
  mkdir -p "$CONFIG_DIR" || return 1
  tmp=$(mktemp "${CONFIG_FILE}.XXXXXX") || return 1
  if [ -f "$CONFIG_FILE" ]; then
    awk -v key="$key" -v val="$quoted" '
      BEGIN { done = 0 }
      $0 ~ "^" key "=" { print key "=" val; done = 1; next }
      { print }
      END { if (!done) print key "=" val }
    ' "$CONFIG_FILE" > "$tmp"
  else
    printf '%s=%s\n' "$key" "$quoted" > "$tmp"
  fi
  mv "$tmp" "$CONFIG_FILE"
}

feature_enabled() {
  local key
  key=$(feature_key "$1") || return 1
  case "$(value_of "$key")" in
    1|true|TRUE|yes|YES|on|ON) return 0 ;;
    *) return 1 ;;
  esac
}

missing_release_branch_inputs() {
  local missing=""
  [ -n "$(value_of STUDIO_RELEASE_BRANCH_DEFAULT_BASE)" ] || missing="${missing} default_release_base"
  [ -n "$(value_of STUDIO_RELEASE_BRANCH_PATTERN)" ] || missing="${missing} branch_pattern"
  printf '%s\n' "${missing# }"
}

cmd_list() {
  local feature key status missing
  printf 'Project: %s\n' "$PROJECT"
  printf 'Config: %s\n\n' "$CONFIG_FILE"
  printf '%-28s %-10s %s\n' "FEATURE" "STATUS" "DETAIL"
  while IFS= read -r feature; do
    key=$(feature_key "$feature")
    if feature_enabled "$feature"; then status="enabled"; else status="disabled"; fi
    missing=$(missing_release_branch_inputs)
    if [ -n "$missing" ]; then
      printf '%-28s %-10s missing:%s\n' "$feature" "$status" " $missing"
    else
      printf '%-28s %-10s %s\n' "$feature" "$status" "$(feature_description "$feature")"
    fi
    [ -n "$key" ] || true
  done <<EOF
$(feature_names)
EOF
}

cmd_get() {
  local name="${1:?usage: get <feature|setting>}" key
  if feature_exists "$name"; then
    key=$(feature_key "$name")
    printf '%s=%s\n' "$key" "$(value_of "$key")"
    return 0
  fi
  key=$(setting_key "$name") || {
    printf 'manager-feature-config: unknown feature or setting: %s\n' "$name" >&2
    return 2
  }
  printf '%s=%s\n' "$key" "$(value_of "$key")"
}

cmd_enable() {
  local feature="${1:?usage: enable <feature> [options]}" base="" pattern="" key missing
  shift
  feature_exists "$feature" || { printf 'manager-feature-config: unknown feature: %s\n' "$feature" >&2; return 2; }
  while [ $# -gt 0 ]; do
    case "$1" in
      --default-release-base) base="${2:?--default-release-base requires value}"; shift 2 ;;
      --branch-pattern) pattern="${2:?--branch-pattern requires value}"; shift 2 ;;
      --dry-run) DRY_RUN=1; shift ;;
      *) printf 'manager-feature-config: enable unknown arg: %s\n' "$1" >&2; return 2 ;;
    esac
  done
  [ -n "$base" ] && write_setting STUDIO_RELEASE_BRANCH_DEFAULT_BASE "$base"
  [ -n "$pattern" ] && write_setting STUDIO_RELEASE_BRANCH_PATTERN "$pattern"
  missing=$(missing_release_branch_inputs)
  if [ -n "$missing" ]; then
    printf 'manager-feature-config: cannot enable %s; missing required input(s): %s\n' "$feature" "$missing" >&2
    printf 'fix: add --default-release-base <branch> --branch-pattern <pattern>\n' >&2
    return 2
  fi
  key=$(feature_key "$feature")
  write_setting "$key" "1"
  if [ "$DRY_RUN" -eq 1 ]; then
    printf 'dry-run: would enable %s for project %s\n' "$feature" "$PROJECT"
  else
    printf 'enabled %s for project %s\n' "$feature" "$PROJECT"
    printf 'config: %s\n' "$CONFIG_FILE"
  fi
}

cmd_disable() {
  local feature="${1:?usage: disable <feature>}" key
  feature_exists "$feature" || { printf 'manager-feature-config: unknown feature: %s\n' "$feature" >&2; return 2; }
  key=$(feature_key "$feature")
  write_setting "$key" "0"
  if [ "$DRY_RUN" -eq 1 ]; then
    printf 'dry-run: would disable %s for project %s\n' "$feature" "$PROJECT"
  else
    printf 'disabled %s for project %s\n' "$feature" "$PROJECT"
  fi
}

cmd_set() {
  local name="${1:?usage: set <setting> <value>}" value="${2:?usage: set <setting> <value>}" key
  key=$(setting_key "$name") || {
    printf 'manager-feature-config: unknown setting: %s\n' "$name" >&2
    return 2
  }
  write_setting "$key" "$value"
  if [ "$DRY_RUN" -eq 1 ]; then
    printf 'dry-run: would set %s for project %s\n' "$key" "$PROJECT"
  else
    printf 'set %s for project %s\n' "$key" "$PROJECT"
  fi
}

doctor_feature() {
  local feature="$1" missing
  feature_exists "$feature" || { printf 'ERROR %s unknown feature\n' "$feature"; return 2; }
  missing=$(missing_release_branch_inputs)
  if ! feature_enabled "$feature"; then
    printf 'OK %s disabled\n' "$feature"
    return 0
  fi
  if [ -n "$missing" ]; then
    printf 'ERROR %s enabled but missing:%s\n' "$feature" " $missing"
    return 1
  fi
  printf 'OK %s enabled\n' "$feature"
}

cmd_doctor() {
  local feature="${1:-}" rc=0
  printf 'Project: %s\n' "$PROJECT"
  printf 'Config: %s\n' "$CONFIG_FILE"
  if [ -n "$feature" ]; then
    doctor_feature "$feature" || rc=$?
  else
    doctor_feature release_branch_workflow || rc=$?
  fi
  return "$rc"
}

case "$COMMAND" in
  list) cmd_list "$@" ;;
  get) cmd_get "$@" ;;
  enable) cmd_enable "$@" ;;
  disable) cmd_disable "$@" ;;
  set) cmd_set "$@" ;;
  doctor) cmd_doctor "$@" ;;
  *) printf 'manager-feature-config: unknown command: %s\n' "$COMMAND" >&2; usage >&2; exit 2 ;;
esac
